[build]
  publish = "."
  
[[redirects]]
  from = "/api/*"
  to = "https://crypto-production-fc43.up.railway.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


